FROM rust:1.86.0-alpine3.21

WORKDIR /app

RUN apk add --no-cache build-base linux-headers curl

COPY Cargo.toml .
RUN cargo install cargo-watch
COPY . .

# Открываем порт
EXPOSE 8888

# Команда запуска
CMD ["cargo", "watch", "--poll", "-x", "run -p cmd --bin app"]
