openapi: 3.1.0
info:
  title: cmd
  description: ''
  license:
    name: ''
  version: 0.1.0
paths:
  /api/v1/customer/hello:
    get:
      tags:
      - customer
      summary: GET /api/v1/customer/hello
      operationId: hello_handler
      responses:
        '200':
          description: Hello from Customer v1
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloResponse'
components:
  schemas:
    HelloResponse:
      type: object
      required:
      - message
      properties:
        message:
          type: string
